#macro SEQTYPE_NULL -1
#macro SEQTYPE_LABEL -2
#macro SEQTYPE_LINES 0
#macro SEQTYPE_WAIT 1
#macro SEQTYPE_CHOICES 2
#macro SEQTYPE_SCREEN 3
#macro SEQTYPE_AUDIO 4
#macro SEQTYPE_MUSIC 5
#macro SEQTYPE_GOTO 6

#macro SEQI_SIZE -1
#macro SEQI_COUNT -1
#macro SEQI_TIME -1
#macro SEQI_TARGET -2
#macro SEQI_LINE -3
#macro SEQI_WAV -4
#macro SEQI_TYPE -5
#macro SEQI_ID -6
#macro SEQI_FACING -7
#macro SEQI_ENDACTION -8
#macro SEQI_JUMP_OFFSET 100

#macro SEQWAIT_INPUT 0
#macro SEQWAIT_TIME 1

#macro SEQEND_NONE 0
#macro SEQEND_AUTO 1
#macro SEQEND_ORGANIC 2

#macro SEQI_SCREEN_R -6
#macro SEQI_SCREEN_G -7
#macro SEQI_SCREEN_B -8
#macro SEQSCREEN_NONE 0
#macro SEQSCREEN_FADEIN 1
#macro SEQSCREEN_FADEOUT 2

#macro SEQI_AUDIO_FILE -4
#macro SEQI_AUDIO_STOP -5
#macro SEQI_AUDIO_LOOP -6
#macro SEQI_AUDIO_STREAMED -7
#macro SEQI_AUDIO_PITCH -8

#macro SEQMUSIC_PLAY 0
#macro SEQMUSIC_UPDATE 1
#macro SEQI_MUSIC_OFFSET 100

#macro SEQI_MUSIC_TRACKCOUNT -1