#macro SEQTYPE_NULL -1
#macro SEQTYPE_LABEL -2
#macro SEQTYPE_LINES 0
#macro SEQTYPE_WAIT 1
#macro SEQTYPE_CHOICES 2
#macro SEQTYPE_SCREEN 3
#macro SEQTYPE_AUDIO 4
#macro SEQTYPE_MUSIC 5
#macro SEQTYPE_GOTO 6
#macro SEQTYPE_GOTO_IF_COMPANION 60
#macro SEQTYPE_GOTO_IF_FLAG 61
#macro SEQTYPE_AI 7
#macro SEQTYPE_PALETTE 8
#macro SEQTYPE_SIGNAL 9
#macro SEQTYPE_EMOTE 10
#macro SEQTYPE_FLAGS 11
#macro SEQTYPE_WORLD 12
#macro SEQTYPE_PORTRAIT 13
#macro SEQTYPE_COMPANION 14
#macro SEQTYPE_SPAWNSTATE 15

#macro SEQI_SIZE -1
#macro SEQI_COUNT -1
#macro SEQI_TIME -1
#macro SEQI_TARGET -2
#macro SEQI_LINE -3
#macro SEQI_WAV -4
#macro SEQI_TYPE -5
#macro SEQI_ID -6
#macro SEQI_FACING -7
#macro SEQI_ENDACTION -8
#macro SEQI_STYLE -9
#macro SEQI_JUMP_OFFSET 100
#macro SEQI_LINE_OFFSET_MALE 200
#macro SEQI_LINE_OFFSET_FEMALE 300
#macro SEQI_LINE_OFFSET_NONBI 400

#macro kLinesStyle_Default 0
#macro kLinesStyle_Portrait 1

#macro SEQI_FACING_LEFT -1
#macro SEQI_FACING_RIGHT 1
#macro SEQI_FACING_UP -2
#macro SEQI_FACING_DOWN 2

#macro SEQWAIT_INPUT 0
#macro SEQWAIT_TIME 1
#macro SEQWAIT_PLAYERDISTANCE 2
#macro SEQWAIT_AI 3

#macro SEQI_GOTO_FLAGID 30
#macro SEQI_GOTO_FLAGVALUE 31
#macro SEQI_GOTO_FLAGCOMPARE 32
#macro SEQI_GOTO_COMPWITH 33
#macro SEQI_GOTO_COMPNOTWITH 34

#macro SEQI_WAIT_AIACTION -21
#macro SEQI_WAIT_DISTANCE -22

#macro SEQEND_NONE 0
#macro SEQEND_AUTO 1
#macro SEQEND_ORGANIC 2

#macro SEQI_SCREEN_R -6
#macro SEQI_SCREEN_G -7
#macro SEQI_SCREEN_B -8
#macro SEQI_SCREEN_SHAKE -9
#macro SEQI_SCREEN_LENGTH -10
#macro SEQSCREEN_NONE 0
#macro SEQSCREEN_FADEIN 1
#macro SEQSCREEN_FADEOUT 2
#macro SEQSCREEN_HOLD 3
#macro SEQSCREEN_SHAKE 4
#macro SEQSCREEN_CTSIN 5
#macro SEQSCREEN_CTSOUT 6

#macro SEQI_AUDIO_FILE -4
#macro SEQI_AUDIO_STOP -5
#macro SEQI_AUDIO_LOOP -6
#macro SEQI_AUDIO_STREAMED -7
#macro SEQI_AUDIO_PITCH -8

#macro SEQMUSIC_PLAY 0
#macro SEQMUSIC_UPDATE 1
#macro SEQI_MUSIC_OFFSET 100

#macro SEQI_MUSIC_TRACKCOUNT -1

#macro SEQI_AI_STYLE -11
#macro SEQI_AI_COMMAND -12
#macro SEQI_AI_POS_X -13
#macro SEQI_AI_POS_Y -14
#macro SEQI_AI_POS_Z -15
#macro SEQI_AI_POS_ORIGIN -20
#macro SEQI_AI_ANIMATION -16
#macro SEQI_AI_LOOPED -17
#macro SEQI_AI_SPEED -18

#macro SEQI_WORLD_COMMAND -5
#macro SEQI_WORLD_CMD_ARG -2
#macro SEQWORLD_TIME 0
#macro SEQWORLD_EVENT 1

#macro SEQI_PORTRAIT_INDEX -1
#macro SEQI_PORTRAIT_ALIGNMENT -20
#macro SEQI_PORTRAIT_ACTION -12
#macro SEQI_PORTRAIT_POS -13
#macro SEQI_PORTRAIT_EXPRESSION -9
#macro SEQI_PORTRAIT_SPRITE -16
#macro SEQI_PORTRAIT_FACING -7

#macro kCompareOpEqual 0
#macro kCompareOpGreater 1
#macro kCompareOpLess 2
#macro kCompareOpGreaterEqual 3
#macro kCompareOpLessEqual 4
#macro kCompareOpNotEqual 5

#macro SEQI_SPAWNSTATE_SPAWNOBJECT -11
#macro SEQI_SPAWNSTATE_DELETEOBJECT -12
#macro SEQI_SPAWNSTATE_POS_X -13
#macro SEQI_SPAWNSTATE_POS_Y -14
#macro SEQI_SPAWNSTATE_POS_Z -15